In [71]:
import torch

#### Define netural network layers 

In [124]:
W1 = torch.tensor([[1.,1.], [1.,1.]], requires_grad = True)
W2 = torch.tensor([1., -2.], requires_grad = True)
b12 = torch.tensor([-0.5, 1.5], requires_grad = True)
b3 = torch.tensor(-0.5, requires_grad = True)
x = torch.tensor([1., 0.])

#### Define neural network computations

In [125]:
NN = lambda x : torch.sigmoid(torch.matmul(W2,torch.sigmoid(torch.matmul(W1,x)+b12))+b3)

#### Alternate simplified NN definition

In [126]:
# def NN(x):
#     z1 = torch.matmul(W1, x) + b12
#     a1 = torch.sigmoid(z1) 
#     z2 = torch.matmul(W2, n2) + b3
#     a2 = torch.sigmoid(z2)
#     return a2

#### Feed x to NN

In [127]:
NN(x)

tensor(0.1511, grad_fn=<SigmoidBackward0>)

#### Run backpropagation using PyTorch's backward() function

In [128]:
NN(x).backward()

#### Check all gradient values

In [129]:
print(W1.grad)

tensor([[ 0.0301,  0.0000],
        [-0.0180, -0.0000]])


In [130]:
print(W2.grad)

tensor([0.0799, 0.1186])


In [131]:
print(b12.grad)

tensor([ 0.0301, -0.0180])


In [132]:
print(b3.grad)

tensor(0.1283)
