## MLP for XOR

In [1]:
import numpy as np

#### Define class MLP

In [17]:
class MLP: 
    def __init__(self, eta=0.5, epochs=10000):
        self.eta = eta
        self.epochs = epochs
        
        # Input to hidden layer
        self.W1 = np.random.randn(2, 2) * 0.5
        self.b1 = np.zeros((1, 2))
        
        #Hidden layer to output
        self.W2 = np.random.randn(2, 1) * 0.5
        self.b2 = np.zeros((1, 1))

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def sigmoid_derivative(self, a):
        return a * (1 - a)

    def forward(self, X):
        #Hidden layer
        self.z1 = X @ self.W1 + self.b1 
        self.a1 = self.sigmoid(self.z1)
        
        #Output layer
        self.z2 = self.a1 @ self.W2 + self.b2
        self.a2 = self.sigmoid(self.z2)

        return self.a2

    def backward(self, X, y):
        n = len(X) #number of data rows

        #Outer layer  

        dL_da2 = (2/n)* (self.a2 - y)
        da2_dz2 = self.sigmoid_derivative(self.a2)

        # using chain rule for derivatives
        dL_dz2 = dL_da2 * da2_dz2

        self.dL_dW2 = (self.a1.T @ dL_dz2)   
        self.dL_db2 = np.sum(dL_dz2, axis = 0, keepdims=True) 

        #Hidden layer
        dL_da1 = dL_dz2 @ self.W2.T
        da1_dz1 = self.sigmoid_derivative(self.a1)
        dL_dz1 = dL_da1 * da1_dz1

        self.dL_dW1 = X.T @ dL_dz1
        self.dL_db1 = np.sum(dL_dz1, axis=0, keepdims=True)

    def train(self, X, y):
        for epoch in range(self.epochs):
            y_pred = self.forward(X)
            loss = np.mean((y_pred - y)**2)  #MSE
            self.backward(X, y)

            #update weights and biases
            self.W2 = self.W2 - self.eta * self.dL_dW2
            self.b2 = self.b2 - self.eta * self.dL_db2
            self.W1 = self.W1 - self.eta * self.dL_dW1
            self.b1 = self.b1 - self.eta * self.dL_db1

            if epoch % 1000 == 0:
                print(f"Epoch {epoch}, Loss: {loss: .6f}")
    
    def predict(self, X):
        probabilties = self.forward(X)
        return (probabilties >= 0.5).astype(int)

        

In [14]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

nn = MLP(eta=1.0, epochs = 10000)
nn.train(X, y)

Epoch 0, Loss:  0.252576
Epoch 1000, Loss:  0.241445
Epoch 2000, Loss:  0.007611
Epoch 3000, Loss:  0.002192
Epoch 4000, Loss:  0.001234
Epoch 5000, Loss:  0.000850
Epoch 6000, Loss:  0.000645
Epoch 7000, Loss:  0.000518
Epoch 8000, Loss:  0.000432
Epoch 9000, Loss:  0.000370


In [16]:
print("\nPredictions:")
print(nn.predict(X))

print("W1:\n", nn.W1)
print("b1:\n", nn.b1)
print("W2:\n", nn.W2)
print("b2:\n", nn.b2)


Predictions:
[[0]
 [1]
 [1]
 [0]]
W1:
 [[4.56793664 6.43731953]
 [4.56999255 6.44568745]]
b1:
 [[-7.01268237 -2.86048208]]
W2:
 [[-10.23101013]
 [  9.5334938 ]]
b2:
 [[-4.40770167]]
